### PR TITLE
refactor(openai): resolve exact catalog identities

### LINKED ISSUE #1209: design(openai): define catalog identity and capability resolution semantics
## Problem

`ModelIdRef` is intentionally a lossless syntax view only. A slash can be a provider qualifier, part of a provider-native model ID such as `BAAI/bge-m3`, or part of an OpenAI pricing-only catalog key such as `1024-x-1024/dall-e-2`. The OpenAI registry therefore cannot infer catalog identity, aliases, or routing semantics from the first segment alone.

Prior review cycles showed that combining syntax parsing with catalog lookup caused ambiguous lookup ordering, double qualification, case-normalization drift, unreachable pricing-only keys, and model/provider capability mismatches.

## Scope

- Design an explicit OpenAI catalog identity abstraction separate from `ModelIdRef` syntax parsing.
- Define how raw wire IDs, public model IDs, stored catalog keys, and explicit aliases relate.
- Specify precedence for exact catalog keys, qualified aliases, already-qualified stored keys, and pricing-only slash-bearing keys.
- Specify provider-segment case behavior without making model IDs case-insensitive.
- Reject malformed double qualification and prefix/suffix lookalikes without name-shape heuristics.
- Define how alias resolution interacts with model-specific and provider-level capability semantics.
- Document how this design composes with configuration-aware Azure/Azure AI and fine-tune identity work in #1207.
- Document error propagation boundaries shared with token-count/spend work in #1208.

## Acceptance criteria

- A written invariant table covers unqualified IDs, explicit `openai/` IDs, already-qualified catalog keys, pricing-only slash keys, nested provider-native IDs, aliases, wrong providers, mixed-case providers, model-case mismatches, and double qualification.
- The design keeps the outbound wire ID lossless and never treats `ModelIdRef::provider()` as validated provider identity.
- Catalog acceptance uses exact entries or explicit aliases only; no prefix, date-shape, family-shape, or provider-name heuristic.
- Capability routing behavior is specified for both exact catalog hits and qualified aliases, including capabilities absent from per-model vectors.
- The implementation plan identifies focused RED/GREEN tests and consumer migration order.

## Non-goals

- This issue does not change the parser introduced by #1205/#1206.
- This issue does not implement Azure deployment identity (#1207) or token/spend error propagation (#1208).

### PR DESCRIPTION
**Pull request by majiayu000**
## Summary

- add a borrowed, exact-only OpenAI catalog identity resolver on top of the lossless `ModelIdRef` parser
- preserve raw wire IDs while resolving unqualified and single-layer `openai/` identifiers
- distinguish callable, pricing-only, and unresolved runtime states through capability and supported-parameter dispatch
- keep raw slash-bearing pricing keys reachable without granting them runnable-model capabilities
- avoid registry-wide scans for ordinary provider-qualified IDs; raw and peeled keys use exact hash lookups
- record only officially documented GPT-5.5 / GPT-5.5 Pro snapshot-to-base identities

## Resolution contract

- raw exact catalog lookup always wins
- the provider segment is ASCII-case-insensitive; the model segment remains case-sensitive
- only one OpenAI provider layer is removed
- no prefix, suffix, date-shape, family-shape, or last-segment inference
- callable entries use model-specific capabilities and parameters
- pricing-only exact entries are explicitly unsupported for Chat, streaming, Embeddings, and OpenAI parameters
- unresolved custom deployments retain the existing provider-level pass-through contract
- slash-bearing pricing entries expose catalog metadata but no capability identity
- dated/base relationships are exact declarations with official sources

## Review fix

- replace the `Option` collapse at production dispatch with explicit `Callable`, `PricingOnly`, and `Unresolved(error)` states
- add production `Provider::supports_capability_for_model` coverage for ChatCompletion, ChatCompletionStream, and Embeddings
- keep generic parameter fallback only for unresolved deployments; pricing-only identities return no supported parameters
- replace the qualified-key full-registry scan with raw exact lookup plus at most two O(1) `HashMap` lookups; mixed provider casing allocates only the normalized provider-qualified key

## Scope

Changed files are limited to:

- `src/core/providers/openai/models/model_id.rs`
- `src/core/providers/openai/models/mod.rs`
- `src/core/providers/openai/models/registry.rs`
- `src/core/providers/openai/client.rs`
- `src/core/providers/openai/client_tests/provider_support_tests.rs`
- `src/core/providers/capability_dispatch.rs`

No model catalog additions, central pricing changes, Azure deployment identity, token/spend handling, SDK/preset work, or #1202 changes.

## Verification

- TDD RED: pricing-only identity inherited ChatCompletion in production dispatch
- TDD RED: pricing-only identity advertised generic OpenAI chat parameters
- resolver/runtime-state tests: 7 passed
- registry tests: 9 passed
- OpenAI provider-support tests: 23 passed
- production capability-dispatch tests: 4 passed
- `cargo fmt --all -- --check`
- `cargo check`
- `cargo clippy --all-targets -- -D warnings`
- bounded `cargo test --lib`: 9,160 passed, 1 ignored

## Sources

- https://developers.openai.com/api/docs/models/gpt-5.5
- https://developers.openai.com/api/docs/models/gpt-5.5-pro

Depends on #1206 and is stacked on exact head `618c35a973180114c209f959193ac1198336841e`.

Fixes #1209

## Review fix cycle 2

- split runtime resolution into exact callable, pricing-only, unregistered unqualified deployment, and invalid identity states
- retain provider pass-through only for non-empty unqualified IDs with no slash
- fail closed for wrong providers, double OpenAI qualification, explicit openai/<unknown> IDs, and all unknown slash-bearing keys
- cover ChatCompletion, ChatCompletionStream, Embeddings, and supported-parameter dispatch with anthropic/gpt-4, openai/openai/gpt-4, openai/fake-gpt-5, unknown/a/b, and custom-openai-deployment
- preserve pricing-only denial and O(1) exact resolver lookup

Cycle-2 verification: resolver 8 passed; registry 9 passed; provider-support 24 passed; capability-dispatch 5 passed; fmt, check, clippy, and diff-check passed. The bounded full lib result from cycle 1 remains 9,160 passed / 1 ignored and was not rerun.

### CODE REVIEW

**Comment by majiayu000** [comment]
## REVIEW_LOOP freeze

This draft is frozen at current head and will not receive a fourth patch cycle.

Across three review rounds, the implementation repeatedly tried to decide whether an unregistered name was a deployment by inspecting model-string syntax. The latest counterexamples show that slash/no-slash and whitespace validation cannot establish deployment identity. Adding another whitespace regex would move the false-positive boundary rather than fix the authority problem.

Review evidence: `/private/tmp/litellm-rs-artifacts/tranche-006/review-1229-r3/summary.md`

Replacement design: #1231 introduces a config-backed model identity authority. A deployment may pass through only when an exact resolved deployment configuration exists; catalog callable, pricing-only, configured deployment, and invalid identities become exhaustive typed results shared by capability and pricing consumers.

Keep this PR draft/open for evidence. Do not resolve its remaining review threads, mark ready, merge, or continue implementation here.

**Comment by majiayu000** [comment]
Superseded by the merged config-backed identity authority delivered through #1243, #1244, and #1233. Those PRs preserve exact catalog classification, raw wire identity, explicit deployment mappings, provider-scoped pricing, and fail-closed capability routing. Keeping this frozen branch as review evidence; no further patch cycle will be applied here.
