### ISSUE TITLE
design(openai): define catalog identity and capability resolution semantics

### ISSUE THREAD

**Issue by majiayu000** [majiayu000/litellm-rs#1209]
## Problem

`ModelIdRef` is intentionally a lossless syntax view only. A slash can be a provider qualifier, part of a provider-native model ID such as `BAAI/bge-m3`, or part of an OpenAI pricing-only catalog key such as `1024-x-1024/dall-e-2`. The OpenAI registry therefore cannot infer catalog identity, aliases, or routing semantics from the first segment alone.

Prior review cycles showed that combining syntax parsing with catalog lookup caused ambiguous lookup ordering, double qualification, case-normalization drift, unreachable pricing-only keys, and model/provider capability mismatches.

## Scope

- Design an explicit OpenAI catalog identity abstraction separate from `ModelIdRef` syntax parsing.
- Define how raw wire IDs, public model IDs, stored catalog keys, and explicit aliases relate.
- Specify precedence for exact catalog keys, qualified aliases, already-qualified stored keys, and pricing-only slash-bearing keys.
- Specify provider-segment case behavior without making model IDs case-insensitive.
- Reject malformed double qualification and prefix/suffix lookalikes without name-shape heuristics.
- Define how alias resolution interacts with model-specific and provider-level capability semantics.
- Document how this design composes with configuration-aware Azure/Azure AI and fine-tune identity work in #1207.
- Document error propagation boundaries shared with token-count/spend work in #1208.

## Acceptance criteria

- A written invariant table covers unqualified IDs, explicit `openai/` IDs, already-qualified catalog keys, pricing-only slash keys, nested provider-native IDs, aliases, wrong providers, mixed-case providers, model-case mismatches, and double qualification.
- The design keeps the outbound wire ID lossless and never treats `ModelIdRef::provider()` as validated provider identity.
- Catalog acceptance uses exact entries or explicit aliases only; no prefix, date-shape, family-shape, or provider-name heuristic.
- Capability routing behavior is specified for both exact catalog hits and qualified aliases, including capabilities absent from per-model vectors.
- The implementation plan identifies focused RED/GREEN tests and consumer migration order.

## Non-goals

- This issue does not change the parser introduced by #1205/#1206.
- This issue does not implement Azure deployment identity (#1207) or token/spend error propagation (#1208).

**Comment by majiayu000** [comment]
Implementation design before code (stacked on #1206 exact head `618c35a973180114c209f959193ac1198336841e`):

### Invariants / precedence

| Input | Resolution |
|---|---|
| `gpt-4` | exact registry key only |
| `openai/gpt-4` / `OPENAI/gpt-4` | peel exactly one provider layer; provider comparison is ASCII-case-insensitive; model key remains case-sensitive |
| exact slash-bearing key such as `1024-x-1024/dall-e-2` | raw exact lookup wins before qualifier parsing |
| exact stored `openai/...` key | raw exact entry is retained; any capability identity must come from an explicit alias, never the last path segment |
| unknown / prefix / suffix / fake dated ID | explicit Unknown error; no fuzzy or family/date inference |
| non-OpenAI qualifier | explicit WrongProvider error, unless the complete raw key is itself an exact OpenAI catalog key |
| `openai/openai/...` | explicit malformed/double-qualification error |
| pricing-only slash key | exact catalog/pricing identity is available, but capability identity is absent |
| base and dated IDs | separate exact identities unless an explicit, sourced alias is declared |

The borrowed `ModelIdRef` remains syntax-only and lossless. The semantic resolver returns the original wire ID unchanged plus borrowed exact registry identities. It does not normalize the model segment, infer aliases, or panic.

### Capability semantics

Provider qualification is a syntax policy, not a model-to-model alias. Capability consumers use only the resolver's capability identity. Raw slash-bearing pricing entries fail closed as capability-less unless an exact alias is declared in a small explicit table and its target is also an exact registry entry. No last-segment fallback is permitted. This preserves provider-level fallback outside the registry while preventing pricing rows from impersonating runnable models.

### File boundary

- `src/core/providers/openai/models/model_id.rs` (new semantic resolver types/policy and focused unit tests)
- `src/core/providers/openai/models/mod.rs`
- `src/core/providers/openai/models/registry.rs` (exact lookup integration and registry tests)
- `src/core/providers/openai/client.rs` (only the three existing model-capability/config/supported-params lookups)
- `src/core/providers/openai/client_tests/provider_support_tests.rs`

No static model data, central pricing JSON/authority, Azure consumers (#1207), tokenizer/spend (#1221), SDK/preset, or #1202 changes.

### RED/GREEN acceptance

RED first for exact/unqualified and qualified lookup, provider-case/model-case boundaries, raw native slash precedence, wrong provider, double qualification, unknown collisions/fake dates, pricing-only capability denial, explicit alias validation, and distinct dated/base identities. GREEN will add only the borrowed exact resolver and migrate the three unambiguous OpenAI capability consumers.

**Comment by majiayu000** [comment]
#1231 is the replacement design candidate for this work.

The review loop in #1229 showed that exact OpenAI catalog resolution, pricing-only slash keys, and configured deployment identity must share one authority. The replacement keeps #1206's parser syntax-only and lossless, but makes capability and pricing consumers use an exhaustive `CatalogCallable`, `PricingOnly`, `ConfiguredDeployment`, or `Invalid` result. It preserves raw exact/native-slash precedence and explicit aliases while removing every deployment/catalog name-shape guess.

This issue is therefore a superseded candidate, but should remain open until the replacement PR for #1231 lands and demonstrably preserves this issue's exact lookup, pricing-only, alias, qualifier, collision, and raw-wire-ID acceptance criteria.

**Comment by majiayu000** [comment]
Superseded design is now implemented on main through #1233 (the #1231 config-backed identity authority) and its catalog/runtime integrations in #1243, #1244, and #1247. The exact-key/qualified-key, pricing-only, explicit deployment mapping, fail-closed capability, and lossless raw-wire boundaries were subsequently exercised by the merged OpenAI and xAI catalog PRs. Closing per the issue's stated replacement condition; no parallel semantic resolver is being added.
